export const AGREGAR_PERSONA = 'AGREGAR_PERSONA';
export const AGREGAR_PERSONA_EXITO ='AGREGAR_PERSONA_EXITO';
export const AGREGAR_PERSONA_ERROR = 'AGREGAR_PERSONA_ERROR';

export const COMENZAR_DESCARGA_PERSONA ="COMENZAR_DESCARGA_PERSONA";
export const DESCARGA_PERSONA_EXITO ="DESCARGA_PERSONA_EXITO";
export const DESCARGA_PERSONA_ERROR ="DESCARGA_PERSONA_ERROR";

export const OBTENER_PERSONA_EDITAR ="OBTENER_PERSONA_EDITAR";
export const COMENZAR_EDICION_PERSONA="COMENZAR_EDICION_PERSONA";
export const PERSONA_EDITADA_EXITO="PERSONA_EDITADA_EXITO;"
export const PERSONA_EDITADA_ERROR="PERSONA_EDITADA_ERROR"

